version: "3.4"
services:
  cred-helper:
    build:
      context: ./
      dockerfile: AWS_CRED_HELPER.Dockerfile
    container_name: aws-cred-helper
    volumes:
      - "aws-cred-helper:/go/bin:rw"

  crusher-server:
    network_mode: host
    image: 862866004122.dkr.ecr.us-east-1.amazonaws.com/crusher-server-images
    environment:
      - CRUSHER_ENV=$CRUSHER_ENV
      - MONGODB_CONNECTION_STRING=$MONGODB_CONNECTION_STRING
      - DB_HOST=$DB_HOST
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - BACKEND_URL=$BACKEND_URL
      - FRONTEND_URL=$FRONTEND_URL

  # Check for new images and restart things if a new image exists
  # for any of our containers.
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
      - aws-cred-helper:/go/bin
    environment:
      - HOME=/
      - PATH=$PATH:/go/bin
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIAIEQN54PTYHMYGXVA
      - AWS_SECRET_ACCESS_KEY=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
    command: --interval 15

volumes:
  aws-cred-helper:
    external: true
