export const ACTION_TYPES = {
  INSPECT: "inspect",
  SEO: "seo",
  GET_SEO_META: "GET_SEO_META",
  SET_SEO_META: "SET_SEO_META",
  ASSERT_ELEMENT: "assert_element",
  NETWORK: "network",
  CAPTURE_CONSOLE: "console",
  SCREENSHOT: "screenshot",
  SANITY: "sanity",
  GO_BACK: "go_back",
  GO_FORWARD: "go_forward",
  REFRESH_PAGE: "go_refresh",
  STARTED_RECORDING_EVENTS: "STARTED_RECORDING_EVENTS",
  TOOGLE_INSPECTOR: "TOOGLE_INSPECTOR",
  GET_RECORDING_STATUS: "GET_RECORDING_STATUS",
  RECORDING_STATUS_RESPONSE: "RECORDING_STATUS_RESPONSE",
  GET_USER_AGENT: "GET_USER_AGENT",
  SET_USER_AGENT: "SET_USER_AGENT",
  SHOW_ELEMENT_FORM: "SHOW_ELEMENT_FORM",
};

export const STATE = {
  SEO: "SEO",
};
