
export const CLI_EVENTS = {
    'RAN_CLI_COMMAND' : 'RAN_CLI_COMMAND',
    'UPDATING_VERSION_START': 'UPDATE_VERSION_START',
    'UPDATING_VERSION_COMPLETE': 'UPDATE_VERSION_COMPLETE',
    'UPDATE_VERSION' : 'UPDATE_VERSION'
}

export enum DesktopAppEventsEnum {
    APP_STARTED = 'DESKTOP_APP_STARTED',
    APP_CLOSED = 'DESKTOP_APP_CLOSED',
    PAGE_OPEN = 'PAGE_OPEN',
    RECORDER_PAGE_OPEN = "RECORDER_PAGE_OPEN",

    DEEPLINK_RUN_LOCAL_BUILD = "DEEPLINK_RUN_LOCAL_BUILD",
    TRIGGER_LOCAL_BUILD = "TRIGGER_LOCAL_BUILD",
    
    OPEN_CREATE_TEST = "OPEN_CREATE_TEST",
    OPEN_EDIT_TEST = "OPEN_EDIT_TEST",
    LOCAL_TEST_RUN = "LOCAL_TEST_RUN",

    SAVE_STEP = 'SAVE_STEP',
};

export enum ServerEventsEnum {
    BUILD_TRIGGERED = 'BUILD_TRIGGERED',
    BUILD_FINISHED = 'BUILD_FINISHED',

    LINK_GITHUB_REPO = 'LINK_GITHUB_REPO',
    LINK_VERCEL_REPO = 'LINK_VERCEL_REPO',

    SET_SLACK_INTEGRATION_CHANNELS = 'SET_SLACK_INTEGRATION_CHANNELS',
}