
export const CLI_EVENTS = {
    'RAN_CLI_COMMAND' : 'RAN_CLI_COMMAND',
    'UPDATING_VERSION_START': 'UPDATE_VERSION_START',
    'UPDATING_VERSION_COMPLETE': 'UPDATE_VERSION_COMPLETE',
    'UPDATE_VERSION' : 'UPDATE_VERSION'
}