
export const CLI_EVENTS = {
    'RAN_CLI_COMMAND' : 'RAN_CLI_COMMAND',
    'UPDATING_VERSION_START': 'UPDATE_VERSION_START',
    'UPDATING_VERSION_COMPLETE': 'UPDATE_VERSION_COMPLETE',
    'UPDATE_VERSION' : 'UPDATE_VERSION'
}

export enum DesktopAppEventsEnum {
    APP_STARTED = 'DESKTOP_APP_STARTED',
    APP_CLOSED = 'DESKTOP_APP_CLOSED',
    PAGE_OPEN = 'PAGE_OPEN',
    RECORDER_PAGE_OPEN = "RECORDER_PAGE_OPEN",

    DEEPLINK_RUN_LOCAL_BUILD = "DEEPLINK_RUN_LOCAL_BUILD",
    TRIGGER_LOCAL_BUILD = "TRIGGER_LOCAL_BUILD",
    
    EXECUTING_STEP = "EXECUTING_STEP",
    
    SAVE_TEST = "SAVE_TEST",
    UPDATE_TEST = "UPDATE_TEST",
    REVERIFY_CURRENT_TEST = "REVERIFY_CURRENT_TEST",
};

export enum ServerEventsEnum {
    BUILD_TRIGGERED = 'BUILD_TRIGGERED',
    BUILD_FINISHED = 'BUILD_FINISHED',

    LINK_GITHUB_REPO = 'LINK_GITHUB_REPO',
    LINK_VERCEL_REPO = 'LINK_VERCEL_REPO',

    SET_SLACK_INTEGRATION_CHANNELS = 'SET_SLACK_INTEGRATION_CHANNELS',
}