image:
  file: docker/gitpod/Dockerfile

ports:
  - port: 3000
    onOpen: 'open-browser'
    visibility: 'public'

tasks:
  - name: 'Start redis-server'
    command: 'redis-server'
  - name: 'Start crusher app'
    init: pnpm install && yarn setup:ee && cp ecosystem.config.sample.js ecosystem.config.js && rm -f .env && cp configs/.env.gitpod .env && node setup/dbMigration.js
    command: "pm2 start"
    openMode: tab-after
