export enum ACTIONS_MODAL_STATE {
	SEO_VALIDATION = "SEO_VALIDATION",
	ASSERT_ELEMENT = "ASSERT_ELEMENT",
	WAIT_SECONDS = "WAIT_SECONDS",
	ELEMENT_CUSTOM_SCRIPT = "ELEMENT_CUSTOM_SCRIPT",
	HOW_TO_USE_VIDEO = "HOW_TO_USE_VIDEO",
}
