export enum TOP_LEVEL_ACTION {
	TOGGLE_INSPECT_MODE = "TOGGLE_INSPECT_MODE",
	TAKE_PAGE_SCREENSHOT = "TAKE_PAGE_SCREENSHOT",
	WAIT = "WAIT",
	SHOW_SEO_MODAL = "SHOW_SEO_MODAL",
	CUSTOM_CODE = "CUSTOM_CODE",
}
