export default [
    {
        id: "iphoneXRXSMax",
        name: "iPhone XR, XS Max",
        width: 414,
        height: 896,
        visible: true,
        userAgent: "iPhone",
    },
    {
        id: "iPhone8Plus7Plus6SPlus",
        name: "iPhone 8+, 7+, 6S+",
        width: 414,
        height: 736,
        visible: false,
        userAgent: "iPhone",
    },
    {
        id: "iPhone876S6",
        name: "iPhone 8, 7, 6S, 6",
        width: 375,
        height: 667,
        visible: false,
        userAgent: "iPhone",
    },
    {
        id: "GalaxyS9PlusS8Plus",
        name: "Galaxy S9+, S8+",
        width: 412,
        height: 846,
        visible: true,
        userAgent: "Samsung Phone",
    },
    // {
    //     id: "GalaxyS9NOte8S8",
    //     name: 'Galaxy S9, Note 8, S8',
    //     width: 360,
    //     height: 740,
    //     visible: true,
    //     userAgent: 'Samsung Phone',
    // },
    {
        id: "Pixel33XL",
        name: "Pixel 3, 3 XL",
        width: 393,
        height: 786,
        visible: true,
        userAgent: "Google Pixel",
    },
    {
        id: "GoogleChromeMediumScreen",
        name: "Desktop (1024 * 800)",
        width: 1024,
        height: 800,
        visible: true,
        userAgent: "Google Chrome",
    },
    {
        id: "GoogleChromeLargeScreen",
        name: "Desktop M (1280 * 800)",
        width: 1280,
        height: 800,
        visible: true,
        userAgent: "Google Chrome",
    },
    {
        id: "GoogleChromeLargeScreen",
        name: "Desktop L (1440 * 800)",
        width: 1280,
        height: 800,
        visible: true,
        userAgent: "Google Chrome",
    },
    {
        id: "GoogleChromeLargeScreen",
        name: "Desktop XL (1600 * 800)",
        width: 1280,
        height: 800,
        visible: true,
        userAgent: "Google Chrome",
    },
];
