export const NAVIGATE_TO_URL = 'NAVIGATE_TO_URL';
export const CLICK_ON_ELEMENT = "CLICK_ON_ELEMENT";
export const FILL_INPUT_ON_ELEMENT = "FILL_INPUT_ON_ELEMENT";
export const HOVER_ON_ELEMENT = "HOVER_ON_ELEMENT";
export const SCROLL_TO_VIEW_TO_ELEMENT ="SCROLL_TO_VIEW_TO_ELEMENT";
export const ASSERT_TEXT_OF_ELEMENT="ASSERT_TEXT";
export const EXTRACT_INFO_FROM_ELEMENT = "EXTRACT_INFO_FROM_ELEMENT";
export const SCREENSHOT_OF_ELEMENT = "SCREENSHOT_OF_ELEMENT";
export const BLACKOUT_ELEMENT = "BLACKOUT_ELEMENT";
export const SCREENSHOT_OF_PAGE = "SCREENSHOT_OF_PAGE";

export const WAIT_FOR_ELEMENT = "WAIT_FOR_ELEMENT";
export const SET_DEVICE = 'SET_DEVICE';