export enum TestInstanceResultSetStatus {
	RUNNING_CHECKS = "RUNNING_CHECKS",
	FINISHED_RUNNING_CHECKS = "FINISHED_RUNNING_CHECKS",
	ERROR_RUNNING_CHECKS = "ERROR_RUNNING_CHECKS",
	TIMEOUT = "TIMEOUT",
}
