const TEST_EXECUTION_QUEUE = "TEST_EXECUTION_QUEUE";
const VIDEO_PROCESSOR_QUEUE = "VIDEO_PROCESSOR_QUEUE";
const TEST_COMPLETE_QUEUE = "TEST_COMPLETE_QUEUE";

export { TEST_EXECUTION_QUEUE, VIDEO_PROCESSOR_QUEUE, TEST_COMPLETE_QUEUE };

