export const EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED";
export const NO_TEAM_JOINED = "NO_TEAM_JOINED";
export const SIGNED_UP_WITHOUT_JOINING_TEAM = "SIGNED_UP_WITHOUT_JOINING_TEAM";
export const SIGNED_IN = "SIGNED_IN";
export const USER_NOT_REGISTERED = "USER_NOT_REGISTERED";

export const ERROR_OCCURED_IN_AUTHENTICATION = "ERROR_OCCURED_IN_AUTHENTICATION";

export const TEAM_CREATION_FAILED = "TEAM_CREATION_FAILED";
export const TEAM_CREATED = "TEAM_CREATED";

export const USER_ALREADY_REGISTERED = "USER_ALREADY_REGISTERED";
export const USER_REGISTERED = "USER_REGISTERED";
export const USER_FAILED_TO_REGISTERED = "USER_NOT_REGISTERED";

export const EMAIL_VERIFIED_WITH_VERIFICATION_CODE = "EMAIL_VERIFIED_WITH_VERIFICATION_CODE";
export const INVALID_VERIFICATION_CODE = "INVALID_VARIFICATION_CODE";
export const VERIFICATION_MAIL_SENT = "VERIFICATION_MAIL_SENT";

export const INVALID_TOKEN = "INVALID_TOKEN";

export const TEST_TYPES = {
	DRAFT: "drf",
	SAVED: "tst",
};

export const TEST_INSTANCE_STATUS = {
	CREATED: "CREATED",
	SKIPPED: "SKIPPED",
	ABORTED: "ABORTED",
	FINISHED: "FINISHED",
};

export const JOB_STATUS = {
	CREATED: "CREATED",
	QUEUED: "QUEUED",
	RUNNING: "RUNNING",
	TIMEOUT: "TIMEOUT",
	ABORTED: "ABORTED",
	FINISHED: "FINISHED",
};

export const TEST_INSTANCE_PLATFORM = {
	FIREFOX: "FIREFOX",
	CHROME: "CHROME",
	WEBKIT: "WEBKIT",
};

export interface emailType {
	email: string;
	name: string;
}
