export enum USER_REGISTERED {
	USER_REGISTERED = "USER_REGISTERED",
	USER_NOT_REGISTERED = "USER_NOT_REGISTERED",
}

export enum USER_META_KEYS {
	INITIAL_ONBOARDING = "INITIAL_ONBOARDING",
	SELECTED_PROJECT_ID = "appState.SELECTED_PROJECT_ID",
	LAST_VISITED_URL = "appState.LAST_VISITED_URL",
	TEST_CREATED = "TEST_CREATED",
	RAN_TEST = "RAN_TEST",
	VIEW_REPORT = "VIEW_REPORT",
}

export enum TEAM_META_KEYS {
	TEST_CREATED = "TEST_CREATED",
}

export enum PROJECT_META_KEYS {
	TEST_CREATED = "TEST_CREATED",
	RAN_TEST = "RAN_TEST",
	VIEW_REPORT = "VIEW_REPORT",
	INTEGRATE_WITH_CI = "INTEGRATE_WITH_CI",
}
