export enum USER_REGISTERED {
	USER_REGISTERED = "USER_REGISTERED",
	USER_NOT_REGISTERED = "USER_NOT_REGISTERED",
}

export enum USER_META_KEYS {
	INITIAL_ONBOARDING = "INITIAL_ONBOARDING",
	SELECTED_PROJECT_ID = "appState.SELECTED_PROJECT_ID",
	LAST_VISITED_URL = "appState.LAST_VISITED_URL",
}
