const { IS_PRODUCTION, AWS_CONFIG, LOCAL_STORAGE_ENDPOINT, REDIS_CONFIG, THIRD_PARTY_API_KEYS, MONGODB_CONFIG } = require('../config');

module.exports = {
	TEST_RUNNER_ENV: {
		NODE_ENV: IS_PRODUCTION ? 'production' : 'development',
		/* Runner MongoDB config */
		MONGODB_CONNECTION_STRING: MONGODB_CONFIG.CONNECTION_STRING ? MONGODB_CONFIG.CONNECTION_STRING : null,
		MONGODB_HOST: MONGODB_CONFIG.HOST,
		MONGODB_PORT: MONGODB_CONFIG.PORT,
		MONGODB_USERNAME: MONGODB_CONFIG.USERNAME,
		MONGODB_PASSWORD: MONGODB_CONFIG.PASSWORD,
		MONGODB_DATABASE: MONGODB_CONFIG.DATABASE,
		REDIS_SECURE: REDIS_CONFIG.SECURE,
		/* LogDNA API config */
		LOGDNA_API_KEY: THIRD_PARTY_API_KEYS.LOGDNA,
		/* Runner Redis DB Config */
		REDIS_CONNECTION_STRING: REDIS_CONFIG.CONNECTION_STRING ? REDIS_CONFIG.CONNECTION_STRING : null,
		REDIS_HOST: REDIS_CONFIG.HOST,
		REDIS_PORT: REDIS_CONFIG.PORT,
		REDIS_USER: REDIS_CONFIG.USERNAME,
		REDIS_PASSWORD: REDIS_CONFIG.PASSWORD,
		AWS_ACCESS_KEY_ID: AWS_CONFIG.AWS_ACCESS_KEY_ID,
		AWS_S3_REGION: AWS_CONFIG.AWS_S3_REGION,
		AWS_S3_VIDEO_BUCKET: AWS_CONFIG.AWS_S3_VIDEO_BUCKET,
		AWS_SECRET_ACCESS_KEY: AWS_CONFIG.AWS_SECRET_ACCESS_KEY,
		/* Prod */
		ECS_CONTAINER_METADATA_URI_V4: process.env.ECS_CONTAINER_METADATA_URI_V4 || undefined,
		CRUSHER_SCALE_LABMDA_URL: process.env.CRUSHER_SCALE_LABMDA_URL || undefined,
		LOCAL_STORAGE_ENDPOINT: LOCAL_STORAGE_ENDPOINT,
		/* Segment API Config */
		SEGMENT_API_KEY: THIRD_PARTY_API_KEYS.SEGMENT,
	},
};
