(async () => {
	const { Page, Element, Browser } = require(".//actions/index.ts");
	const playwright = require("playwright");
	const browser = await playwright["firefox"].launch({ headless: false });
	const browserInfo = await Browser.setDevice(
		JSON.parse(
			"{\"type\":\"SET_DEVICE\",\"payload\":{\"meta\":{\"device\":{\"id\":\"GoogleChromeLargeScreen\",\"name\":\"Desktop M (1280 * 800)\",\"width\":1280,\"height\":800,\"visible\":true,\"userAgent\":\"Google Chrome\"},\"userAgent\":{\"name\":\"Google Chrome\",\"value\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36\",\"appVersion\":\"Mac OS X 10.14.0\",\"platform\":\"Mac OS X\"}}}}",
		),
	);
	const browserContext = await browser.newContext({
		userAgent: browserInfo.meta.userAgent,
		viewport: { width: browserInfo.meta.width, height: browserInfo.meta.height },
		recordVideo: { dir: "./video" },
	});

	const page = await browserContext.newPage({});
	const { handlePopup } = require(".//middlewares");
	handlePopup(page, browserContext);
	await Page.navigate(
		JSON.parse(
			"{\"type\":\"NAVIGATE_URL\",\"payload\":{\"selectors\":[{\"type\":\"customFinder\",\"value\":\"#gsr\",\"uniquenessScore\":1},{\"type\":\"xpath\",\"value\":\"BODY\",\"uniquenessScore\":1},{\"type\":\"id\",\"value\":\"#gsr\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"body[jsmodel=\\\"TvHxbe\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"body[jsaction=\\\"VM8bg:.CLIENT;hWT9Jb:.CLIENT;WCulWe:.CLIENT;NTJodf:.CLIENT;szjOR:.CLIENT;PY1zjf:.CLIENT;wnJTPd:.CLIENT;qmWBbf:.CLIENT;tbSCpf:.CLIENT;hwLEjc:.CLIENT;D9uYNe:.CLIENT;SgU1Eb:.CLIENT;FKSkld:.CLIENT;Reiqfc:.CLIENT;TdqOFb:.CLIENT;OIVYlc:.CLIENT;mHat8:.CLIENT;z3NTEf:.CLIENT;i5olzd:.CLIENT;Sc9O1c:.CLIENT;JL9QDc:.CLIENT;kWlxhc:.CLIENT;qGMTIf:.CLIENT\\\"]\",\"uniquenessScore\":1},{\"type\":\"PnC\",\"value\":\"html > #gsr\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":2,\"optimized\":2}}],\"meta\":{\"value\":\"https://www.google.com/\"}},\"url\":\"https://www.google.com/?__crusherAgent__=Google%20Chrome\"}",
		),
		page,
	);

	await Element.screenshot(
		JSON.parse(
			"{\"type\":\"ELEMENT_SCREENSHOT\",\"payload\":{\"selectors\":[{\"type\":\"customFinder\",\"value\":\"div > .A8SBwf > .FPdoLc > center > .gNO89b\",\"uniquenessScore\":1},{\"type\":\"xpath\",\"value\":\"BODY/DIV[2]/DIV[2]/FORM[1]/DIV[2]/DIV[1]/DIV[3]/CENTER[1]/INPUT[1]\",\"uniquenessScore\":1},{\"type\":\"dataAttribute\",\"value\":\"input[data-ved=\\\"0ahUKEwi6leDw-JLuAhVI4zgGHTOuDrgQ4dUDCAs\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[value=\\\"Google Search\\\"]\",\"uniquenessScore\":0.5},{\"type\":\"attribute\",\"value\":\"input[aria-label=\\\"Google Search\\\"]\",\"uniquenessScore\":0.5},{\"type\":\"attribute\",\"value\":\"input[name=\\\"btnK\\\"]\",\"uniquenessScore\":0.5},{\"type\":\"attribute\",\"value\":\"input[type=\\\"submit\\\"]\",\"uniquenessScore\":0.25},{\"type\":\"attribute\",\"value\":\"input[style=\\\"outline-style: none; outline-width: 0px;\\\"]\",\"uniquenessScore\":0.5},{\"type\":\"PnC\",\"value\":\"center:nth-child(1) > .gNO89b\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":2,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\".FPdoLc .gNO89b\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":3,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\".A8SBwf > .FPdoLc .gNO89b\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":4,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"div .FPdoLc .gNO89b\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":5,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"#tsf .FPdoLc .gNO89b\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":6,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"#searchform > #tsf .FPdoLc .gNO89b\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":7,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"#viewport > #searchform > #tsf .FPdoLc .gNO89b\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":8,\"optimized\":2}}],\"meta\":null},\"url\":\"\"}",
		),
		page,
	);

	await Element.click(
		JSON.parse(
			"{\"type\":\"CLICK\",\"payload\":{\"selectors\":[{\"type\":\"customFinder\",\"value\":\".A8SBwf > .RNNXgb > .SDkEP > .a4bIc > .gLFyf\",\"uniquenessScore\":1},{\"type\":\"xpath\",\"value\":\"BODY/DIV[2]/DIV[2]/FORM[1]/DIV[2]/DIV[1]/DIV[1]/DIV[1]/DIV[2]/INPUT[1]\",\"uniquenessScore\":1},{\"type\":\"dataAttribute\",\"value\":\"input[data-ved=\\\"0ahUKEwi6leDw-JLuAhVI4zgGHTOuDrgQ39UDCAQ\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[maxlength=\\\"2048\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[name=\\\"q\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[type=\\\"text\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[jsaction=\\\"paste:puy29d\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[aria-autocomplete=\\\"both\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[aria-haspopup=\\\"false\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[autocapitalize=\\\"off\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[autocomplete=\\\"off\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[autocorrect=\\\"off\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[autofocus=\\\"\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[role=\\\"combobox\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[spellcheck=\\\"false\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[title=\\\"Search\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[value=\\\"\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[aria-label=\\\"Search\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[style=\\\"outline-style: none; outline-width: 0px;\\\"]\",\"uniquenessScore\":0.3333333333333333},{\"type\":\"PnC\",\"value\":\".a4bIc > .gLFyf\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":2,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\".SDkEP .gLFyf\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":3,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\".RNNXgb .gLFyf\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":4,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\".A8SBwf .gLFyf\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":5,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"div .gLFyf\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":6,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"#tsf .gLFyf\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":7,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"#searchform > #tsf .gLFyf\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":8,\"optimized\":2}}],\"meta\":{\"value\":\"\"}},\"url\":\"https://www.google.com/?__crusherAgent__=Google%20Chrome\"}",
		),
		page,
	);

	await Element.addInput(
		JSON.parse(
			"{\"type\":\"ADD_INPUT\",\"payload\":{\"selectors\":[{\"type\":\"customFinder\",\"value\":\".A8SBwf > .RNNXgb > .SDkEP > .a4bIc > .gLFyf\",\"uniquenessScore\":1},{\"type\":\"xpath\",\"value\":\"BODY/DIV[2]/DIV[2]/FORM[1]/DIV[2]/DIV[1]/DIV[1]/DIV[1]/DIV[2]/INPUT[1]\",\"uniquenessScore\":1},{\"type\":\"dataAttribute\",\"value\":\"input[data-ved=\\\"0ahUKEwi6leDw-JLuAhVI4zgGHTOuDrgQ39UDCAQ\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[maxlength=\\\"2048\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[name=\\\"q\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[type=\\\"text\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[jsaction=\\\"paste:puy29d\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[aria-autocomplete=\\\"both\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[aria-haspopup=\\\"false\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[autocapitalize=\\\"off\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[autocomplete=\\\"off\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[autocorrect=\\\"off\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[autofocus=\\\"\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[role=\\\"combobox\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[spellcheck=\\\"false\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[title=\\\"Search\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[value=\\\"\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[aria-label=\\\"Search\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[style=\\\"outline-style: none; outline-width: 0px;\\\"]\",\"uniquenessScore\":0.3333333333333333},{\"type\":\"PnC\",\"value\":\".a4bIc > .gLFyf\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":2,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\".SDkEP .gLFyf\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":3,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\".RNNXgb .gLFyf\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":4,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\".A8SBwf .gLFyf\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":5,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"div .gLFyf\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":6,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"#tsf .gLFyf\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":7,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"#searchform > #tsf .gLFyf\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":8,\"optimized\":2}}],\"meta\":{\"value\":[72,101,108,108,111,32,119,111,114,108,100]}},\"url\":\"https://www.google.com/?__crusherAgent__=Google%20Chrome\"}",
		),
		page,
	);

	await Element.click(
		JSON.parse(
			"{\"type\":\"CLICK\",\"payload\":{\"selectors\":[{\"type\":\"customFinder\",\"value\":\"#gsr #main\",\"uniquenessScore\":1},{\"type\":\"xpath\",\"value\":\"BODY/DIV[2]/DIV[4]\",\"uniquenessScore\":1},{\"type\":\"id\",\"value\":\"#main\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"div[style=\\\"outline-style: none; outline-width: 0px;\\\"]\",\"uniquenessScore\":0.09090909090909091},{\"type\":\"PnC\",\"value\":\"#viewport > #main\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":2,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"#gsr #main\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":3,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"html > #gsr #main\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":4,\"optimized\":2}}],\"meta\":{\"value\":\"\"}},\"url\":\"https://www.google.com/?__crusherAgent__=Google%20Chrome\"}",
		),
		page,
	);

	await Element.click(
		JSON.parse(
			"{\"type\":\"CLICK\",\"payload\":{\"selectors\":[{\"type\":\"customFinder\",\"value\":\"div > .A8SBwf > .FPdoLc > center > .gNO89b\",\"uniquenessScore\":1},{\"type\":\"xpath\",\"value\":\"BODY/DIV[2]/DIV[2]/FORM[1]/DIV[2]/DIV[1]/DIV[3]/CENTER[1]/INPUT[1]\",\"uniquenessScore\":1},{\"type\":\"dataAttribute\",\"value\":\"input[data-ved=\\\"0ahUKEwi6leDw-JLuAhVI4zgGHTOuDrgQ4dUDCAs\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"input[value=\\\"Google Search\\\"]\",\"uniquenessScore\":0.5},{\"type\":\"attribute\",\"value\":\"input[aria-label=\\\"Google Search\\\"]\",\"uniquenessScore\":0.5},{\"type\":\"attribute\",\"value\":\"input[name=\\\"btnK\\\"]\",\"uniquenessScore\":0.5},{\"type\":\"attribute\",\"value\":\"input[type=\\\"submit\\\"]\",\"uniquenessScore\":0.25},{\"type\":\"attribute\",\"value\":\"input[style=\\\"outline-style: none; outline-width: 0px;\\\"]\",\"uniquenessScore\":0.3333333333333333},{\"type\":\"PnC\",\"value\":\"center:nth-child(1) > .gNO89b\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":2,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\".FPdoLc .gNO89b\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":3,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\".A8SBwf > .FPdoLc .gNO89b\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":4,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"div .FPdoLc .gNO89b\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":5,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"#tsf .FPdoLc .gNO89b\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":6,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"#searchform > #tsf .FPdoLc .gNO89b\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":7,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"#viewport > #searchform > #tsf .FPdoLc .gNO89b\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":8,\"optimized\":2}}],\"meta\":{\"value\":\"\"}},\"url\":\"https://www.google.com/?__crusherAgent__=Google%20Chrome\"}",
		),
		page,
	);

	await Element.screenshot(
		JSON.parse(
			"{\"type\":\"ELEMENT_SCREENSHOT\",\"payload\":{\"selectors\":[{\"type\":\"customFinder\",\"value\":\"div > .A8SBwf > .logo > #logo > img\",\"uniquenessScore\":1},{\"type\":\"xpath\",\"value\":\"BODY/DIV[4]/FORM[1]/DIV[2]/DIV[1]/DIV[1]/A[1]/IMG[1]\",\"uniquenessScore\":1},{\"type\":\"dataAttribute\",\"value\":\"img[data-atf=\\\"1\\\"]\",\"uniquenessScore\":0.08333333333333333},{\"type\":\"attribute\",\"value\":\"img[src=\\\"/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"img[alt=\\\"Google\\\"]\",\"uniquenessScore\":1},{\"type\":\"attribute\",\"value\":\"img[height=\\\"30\\\"]\",\"uniquenessScore\":1},{\"type\":\"PnC\",\"value\":\"#logo > img\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":2,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\".logo img\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":3,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\".A8SBwf img\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":4,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"div > .A8SBwf img\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":5,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"#tsf img\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":6,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"#searchform > #tsf img\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":7,\"optimized\":2}},{\"type\":\"PnC\",\"value\":\"#gsr > #searchform > #tsf img\",\"uniquenessScore\":1,\"meta\":{\"seedLength\":8,\"optimized\":2}}],\"meta\":null},\"url\":\"\"}",
		),
		page,
	);

	await browser.close();
})();
