################################################
# Compile with:
#     sudo docker build -t microsoft/playwright:bionic -f Dockerfile.bionic .
#
# Run with:
#     sudo docker run -d -p --rm --name playwright microsoft/playwright:bionic
#
#################################################

FROM mcr.microsoft.com/playwright:bionic

# 1. Add codebase
VOLUME ["/code"]

WORKDIR /code

RUN npm install -g npm@7.0.3

# 2. Give permission to user to edit it
RUN chown -R pwuser:pwuser ./

# 3. Run everything after as non-privileged user.
USER pwuser


WORKDIR /code/packages/test-runner/

EXPOSE 80

ENTRYPOINT ["npm"]
CMD ["run", "-s", "start"]
