export enum InputNodeTypeEnum {
	CONTENT_EDITABLE = "CONTENT_EDITABLE",
	INPUT = "INPUT",
	CHECKBOX = "CHECKBOX",
	RADIO = "RADIO",
	SELECT = "SELECT",
	MULTISELECT = "MULTISELECT",
	TEXTAREA = "TEXTAREA",
}
