export const EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED";
export const NO_TEAM_JOINED = "NO_TEAM_JOINED";
export const SIGNED_IN = "SIGNED_IN";
export const USER_NOT_REGISTERED = "USER_NOT_REGISTERED";
export const ERROR = "ERROR";

export const TEAM_CREATION_FAILED = "TEAM_CREATION_FAILED";
export const TEAM_CREATED = "TEAM_CREATED";

export const USER_ALREADY_REGISTERED = "USER_ALREADY_REGISTERED";
export const USER_REGISTERED = "USER_REGISTERED";
export const USER_FAILED_TO_REGISTERED = "USER_NOT_REGISTERED";

export const VERIFICATION_MAIL_SENT = "VERIFICATION_MAIL_SENT";

export const USER_STATUS = { NO_TEAM_JOINED: "NO_TEAM_JOINED" };

export const NAVIGATE_URL = "NAVIGATE_URL";
export const CLICK = "CLICK";
export const INPUT = "INPUT";
export const HOVER = "HOVER";
export const SCROLL_TO_VIEW = "SCROLL_TO_VIEW";
export const ASSERT_TEXT = "ASSERT_TEXT";
export const EXTRACT_INFO = "EXTRACT_INFO";
export const SCREENSHOT = "SCREENSHOT";
export const BLACKOUT = "BLACKOUT";
export const WAIT = "WAIT";
export const PAGE_SCREENSHOT = "PAGE_SCREENSHOT";
export const CAPTURE_CONSOLE = "CAPTURE_CONSOLE";
