name: Test electron app

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 16.13.2
          cache: 'yarn'

      - name: Create ecosystem.config.js and Copy .env.sample file
        run: cp ecosystem.config.sample.js ecosystem.config.js && cp .env.sample .env

      - name: Install crusher modules
        run: yarn

      - name: Setup crusher for prod
        run: yarn setup:prod

      - if: matrix.os == 'ubuntu-20.04'
        name: 'Run tests for electron app'
        run: |
         xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn workspace electron-app test
